#!/usr/bin/env bash

set -euo pipefail
GNU_TOOL="make"
#GNU_FTP=https://ftpmirror.gnu.org
#GNU_KEYRING=$GNU_FTP/gnu/gnu-keyring.gpg
GNU_FTP=https://ftp.gnu.org/gnu
GNU_KEYRING=$GNU_FTP/gnu-keyring.gpg
TOOL_NAME="make"
TOOL_TEST="make --version"

GNU_CHECK_SIGNATURES="${GNU_CHECK_SIGNATURES:-strict}"

fail() {
  echo -e "asdf-$TOOL_NAME: $*"
  exit 1
}

curl_opts=(-fsSL)

sort_versions() {
  sed 'h; s/[+-]/./g; s/.p\([[:digit:]]\)/.z\1/; s/$/.z/; G; s/\n/ /' |
    LC_ALL=C sort -t. -k 1,1 -k 2,2n -k 3,3n -k 4,4n -k 5,5n | awk '{print $2}'
}

list_gnu_releases() {
  while read -r line; do
    if [[ "$line" =~ ${GNU_TOOL}-([1-9]+\.[0-9]+(:?\.[0-9]+)*)\.tar\.gz\.sig ]]; then
      echo "${BASH_REMATCH[1]}"
    fi
  done < <(curl "${curl_opts[@]}" ${GNU_FTP}/${GNU_TOOL}/) | uniq
}

list_all_versions() {
  list_gnu_releases
}

download_release() {
  local version filename url sig_url gnu_keyring gpg_command
  version="$1"
  filename="$2"

  url="${GNU_FTP}/${GNU_TOOL}/${GNU_TOOL}-${version}.tar.gz"
  sig_url="${GNU_FTP}/${GNU_TOOL}/${GNU_TOOL}-${version}.tar.gz.sig"
  gnu_keyring=$(dirname "$filename")/gnu-keyring.gpg

  gpg_command="$(command -v gpg gpg2 | head -n 1 || :)"

  if [ -z "${gpg_command}" ]; then
    fail 'gpg or gpg2 command not found. You must install GnuPG'
  fi

  echo "* Downloading $TOOL_NAME release $version..."
  curl "${curl_opts[@]}" -o "$filename" "$url" || fail "Could not download $url"
  curl "${curl_opts[@]}" -o "$filename.sig" "$sig_url" || fail "Could not download signature $sig_url"

  if [[ "${GNU_CHECK_SIGNATURES}" == "strict" ]]; then
    curl "${curl_opts[@]}" -o "$gnu_keyring" "$GNU_KEYRING" || fail "Could not download gpg key $gnu_keyring"
    ${gpg_command} --keyring "$gnu_keyring" --verify "$filename.sig" 2>/dev/null || fail "Failed to GPG verification"
  fi
}

install_version() {
  local install_type="$1"
  local version="$2"
  local install_path="$3"
  local install_log="$ASDF_DOWNLOAD_PATH/install.log"

  if [ "$install_type" != "version" ]; then
    fail "asdf-$TOOL_NAME supports release installs only"
  fi

  (
    mkdir -p "$install_path"
    cd "$ASDF_DOWNLOAD_PATH"

    echo "* Installing $TOOL_NAME release $version..."
    # If the make command is not installed on system old version, may get an error like the following:
    #
    #   config.status: error: Something went wrong bootstrapping makefile fragments
    #      for automatic dependency tracking.  Try re-running configure with the
    #      '--disable-dependency-tracking' option to at least be able to build
    #      the package (albeit without support for automatic dependency tracking).
    #
    # If try to make install in this state, the installation will fail because the
    # Makefile of the po directory does not exist.
    #
    # Will not use make, which is installed on the system, to ensure a reliable build.
    # First run configure to generate build.sh.
    # Then, configure to use the make generated by build.sh and run configure again.
    # At this time, can speed up second time configure by enabling configure caching (-C).
    {
      ./configure -C --prefix="$install_path"
      ./build.sh &&
        PATH=$ASDF_DOWNLOAD_PATH:$PATH ./configure -C --prefix="$install_path" &&
        ./make install
    } &>"$install_log"

    local tool_cmd
    tool_cmd="$(echo "$TOOL_TEST" | cut -d' ' -f1)"
    test -x "$install_path/bin/$tool_cmd" || fail "Expected $install_path/bin/$tool_cmd to be executable."

    echo "$TOOL_NAME $version installation was successful!"
  ) || (
    rm -rf "$install_path"
    fail "An error ocurred while installing $TOOL_NAME $version. install log is $install_log"
  )
}
